// Wave-8 HF-D2 — unit tests for fuseTemplate helper.

import { describe, expect, it } from 'vitest';
import type { Atom, AtomId, Bond, BondId, Command } from '@kendraw/scene';
import {
  RING_TEMPLATE_SMILES,
  fuseTemplate,
  type FuseEndpointResponse,
} from '../templateFusion';

function makeAtom(id: string, x: number, y: number, element = 6): Atom {
  return {
    id: id as AtomId,
    x,
    y,
    element,
    charge: 0,
    radicalCount: 0,
    lonePairs: 0,
  };
}

function makeBond(id: string, from: string, to: string): Bond {
  return {
    id: id as BondId,
    fromAtomId: from as AtomId,
    toAtomId: to as AtomId,
    order: 1,
    style: 'single',
  };
}

const ETHANE_ATOMS: Atom[] = [makeAtom('a1', 0, 0), makeAtom('a2', 1, 0)];
const ETHANE_BONDS: Bond[] = [makeBond('b1', 'a1', 'a2')];

const FUSED_MOL = `  Indigo
  Generated by tests

  7  7  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.2500    1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.7500    1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.5000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.7500   -1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.2500   -1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  3  4  1  0  0  0  0
  4  5  2  0  0  0  0
  5  6  1  0  0  0  0
  6  7  2  0  0  0  0
  7  2  1  0  0  0  0
M  END`;

function responseOk(mol: string): Response {
  return new Response(
    JSON.stringify({ mol_block: mol, success: true } satisfies FuseEndpointResponse),
    { status: 200, headers: { 'Content-Type': 'application/json' } },
  );
}

describe('fuseTemplate', () => {
  it('short-circuits when the page is empty', async () => {
    const dispatched: Command[] = [];
    const r = await fuseTemplate({
      atoms: [],
      bonds: [],
      targetId: 'a1' as AtomId,
      mode: 'atom',
      templateSmiles: 'c1ccccc1',
      dispatch: (c) => dispatched.push(c),
    });
    expect(r.ok).toBe(false);
    expect(r.reason).toBe('empty');
    expect(dispatched).toEqual([]);
  });

  it('refuses when the targetId is not in the page', async () => {
    const dispatched: Command[] = [];
    const r = await fuseTemplate({
      atoms: ETHANE_ATOMS,
      bonds: ETHANE_BONDS,
      targetId: 'missing' as AtomId,
      mode: 'atom',
      templateSmiles: 'c1ccccc1',
      dispatch: (c) => dispatched.push(c),
    });
    expect(r.ok).toBe(false);
    expect(r.reason).toBe('target-missing');
    expect(dispatched).toEqual([]);
  });

  it('reports network errors and dispatches nothing', async () => {
    const dispatched: Command[] = [];
    const r = await fuseTemplate({
      atoms: ETHANE_ATOMS,
      bonds: ETHANE_BONDS,
      targetId: 'a1' as AtomId,
      mode: 'atom',
      templateSmiles: 'c1ccccc1',
      dispatch: (c) => dispatched.push(c),
      fetchImpl: () => Promise.reject(new Error('boom')),
    });
    expect(r.ok).toBe(false);
    expect(r.reason).toBe('network');
    expect(dispatched).toEqual([]);
  });

  it('reports engine failures (success=false) and dispatches nothing', async () => {
    const dispatched: Command[] = [];
    const r = await fuseTemplate({
      atoms: ETHANE_ATOMS,
      bonds: ETHANE_BONDS,
      targetId: 'a1' as AtomId,
      mode: 'atom',
      templateSmiles: 'c1ccccc1',
      dispatch: (c) => dispatched.push(c),
      fetchImpl: () =>
        Promise.resolve(
          new Response(
            JSON.stringify({
              mol_block: '',
              success: false,
              error: 'parse failed',
            } satisfies FuseEndpointResponse),
            { status: 200 },
          ),
        ),
    });
    expect(r.ok).toBe(false);
    expect(r.reason).toBe('engine');
    expect(dispatched).toEqual([]);
  });

  it('on success replaces the entire page with the parsed result', async () => {
    const captured: { url: string; body: string }[] = [];
    const dispatched: Command[] = [];
    const r = await fuseTemplate({
      atoms: ETHANE_ATOMS,
      bonds: ETHANE_BONDS,
      targetId: 'a1' as AtomId,
      mode: 'atom',
      templateSmiles: 'c1ccccc1',
      dispatch: (c) => dispatched.push(c),
      fetchImpl: (input, init) => {
        captured.push({ url: String(input), body: String(init?.body ?? '') });
        return Promise.resolve(responseOk(FUSED_MOL));
      },
    });
    expect(r.ok).toBe(true);
    expect(captured.length).toBe(1);
    const call = captured[0];
    if (!call) throw new Error('fetch not invoked');
    expect(call.url).toContain('/structure/fuse-template');
    const sentBody = JSON.parse(call.body) as Record<string, unknown>;
    expect(sentBody.mode).toBe('atom');
    expect(sentBody.target_index).toBe(0);
    expect(sentBody.template_smiles).toBe('c1ccccc1');

    const removeBatch = dispatched.find((c) => c.type === 'remove-batch');
    expect(removeBatch).toBeDefined();
    const addedAtoms = dispatched.filter((c) => c.type === 'add-atom');
    const addedBonds = dispatched.filter((c) => c.type === 'add-bond');
    expect(addedAtoms.length).toBe(7);
    expect(addedBonds.length).toBe(7);
  });

  it('passes template_anchors when provided', async () => {
    const bodies: string[] = [];
    await fuseTemplate({
      atoms: ETHANE_ATOMS,
      bonds: ETHANE_BONDS,
      targetId: 'b1' as BondId,
      mode: 'bond',
      templateSmiles: 'c1ccccc1',
      templateAnchors: [0, 1],
      dispatch: () => undefined,
      fetchImpl: (_url, init) => {
        bodies.push(String(init?.body ?? ''));
        return Promise.resolve(responseOk(FUSED_MOL));
      },
    });
    const raw = bodies[0];
    if (!raw) throw new Error('fetch not invoked');
    const body = JSON.parse(raw) as Record<string, unknown>;
    expect(body.template_anchors).toEqual([0, 1]);
    expect(body.target_index).toBe(0);
    expect(body.mode).toBe('bond');
  });
});

describe('RING_TEMPLATE_SMILES', () => {
  it('covers all toolbox ring ids', () => {
    expect(RING_TEMPLATE_SMILES.benzene).toBe('c1ccccc1');
    expect(RING_TEMPLATE_SMILES.cyclohexane).toBe('C1CCCCC1');
    expect(RING_TEMPLATE_SMILES.pyridine).toBe('c1ccncc1');
  });
});
